# Generated by Django 4.2.7 on 2023-12-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0005_statsprj'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
